### ISSUE TITLE
Facebook or twitter login

### ISSUE THREAD

**Issue by sirfak** [vbudilov/aws-cognito-ionic2#1]
Hi,

Is there any way to add facebook or twitter login integration ?

tks

**Comment by vbudilov** [comment]
Hi @sirfak , 

FB or TW with Cognito or stand-alone? 

Thanks,
Vladimir

**Comment by sirfak** [comment]
With cognito

**Comment by vbudilov** [comment]
It's just a matter of adding additional buttons and some code that's well documented here: 
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-configuring.html

**Comment by sirfak** [comment]
Great !!

**Comment by mqasem92** [comment]
Please I need more explain !!
