### ISSUE TITLE
Missing credentials in config

### ISSUE THREAD

**Issue by Munnster83** [vbudilov/aws-cognito-ionic2#2]
Hi @vbudilov,

Thanks again for providing the Ionic2 Library, I believe this is more of a bug that I am doing wrong, however I am trying to setup my user pools within AWS console and I think im doing something wrong which is why im getting "Missing credentials in config", when using your credentials it works fine.

I followed this guide (only for the aws console setup) https://www.hawatel.com/blog/aws-cognito-authentication-in-ionic-framework

Is there something blazingly obvious im doing wrong?

Im using this region if it makes any difference?

export let _REGION = "eu-west-1";

**Comment by vbudilov** [comment]
Try following these steps in setting your Cognito User Pool and let me know if that doesn't work:
http://docs.aws.amazon.com/cognito/latest/developerguide/create-new-user-pool-console-quickstart.html

http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html

**Comment by vbudilov** [comment]
The region doesn't matter, as long as you have cognito setup in that particular region (and cognito federated identity)

**Comment by Munnster83** [comment]
Hi Again @vbudilov,

Thanks for the quick response.

I have gone through the documentation and setup different identity and user pools multiple times but with no luck :(

Here is a step by step process of what im doing can you see what im doing wrong? Am i missing a vital stage out?

==========
User Pools
==========
Pool name
	- ionic_user_pool
Attributes
	- email (no alias ticked)
	- no custom attributes added
Policies
	- 8 min length
	- all four required tick boxes checked
Verifications
	- MFA - OFF
	- require verification - Just Email checked
	- no custom addresses added
Devices
	- remember devices - Always
Apps
	- app name - myNewIonicApp
	- App client id - (saved string for later use within app) e.g. 719s43jcbXXXXXXXXXXXXXXXXX
Triggers
	- all set to none
Pool id
	- saved string for later use within app e.g. eu-west-1_QHYXXXXXX

====================
Federated Identities
====================
step 1: create identity pool
	- Identity pool name* - ionic_identities
	- Unauthenticated identities - NOT ticked
	- Authentication providers (cognito tab selected)
		- user pool id - eu-west-1_QHYXXXXXX
		- App client id - 719s43jcbXXXXXXXXXXXXXXXXX
	- Identity pool ID - (saved string for later use within app) eu-west-1:d4711388-8a31-XXXX-XXXX-XXXXXXXXXXXX
	
Your authenticated identities would like access to Cognito.
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "mobileanalytics:PutEvents",
        "cognito-sync:*",
        "cognito-identity:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}

Your unauthenticated identities would like access to Cognito
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "mobileanalytics:PutEvents",
        "cognito-sync:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}

=================================
APP Code in properties.service.ts
=================================
export let _REGION = "eu-west-1";
export let _IDENTITY_POOL_ID = "eu-west-1:d4711388-8a31-XXXX-XXXX-XXXXXXXXXXXX";
export let _USER_POOL_ID = "eu-west-1_QHYXXXXXX";
export let _CLIENT_ID = "719s43jcbXXXXXXXXXXXXXXXXX";

**Comment by Munnster83** [comment]
Also when i look at the response in chrome devtools I get this.

{"__type":"NotAuthorizedException","message":"Unauthenticated access is not supported for this identity pool."}

**Comment by Munnster83** [comment]
Ok so I have done more digging around the "NotAuthorizedException" and it looks like when i created the identity pool within AWS i had not ticket the box "Enable access to unauthenticated identities".

Just curious as to why we would need to enable access for authenticated users for a user to signup and register when we only want to allow autherised users into the app?

Only reason I can think of is that with the aws-javascript sdk we cannot create secrets against the App within the user pool?

**Comment by vbudilov** [comment]
Sometimes you want to merge your guest with your auth user (once that guest authenticates). 
http://docs.aws.amazon.com/cognito/latest/developerguide/switching-identities.html
"Users can begin their life in an application as unauthenticated guests. Eventually they may decide to log in using one of the supported identity providers. Amazon Cognito will ensure that an old identity retains the same unique identifier as the new one, and the profile data will be merged automatically."
