### ISSUE TITLE
Identity Pool Adding users as Unauthenticated on registration

### ISSUE THREAD

**Issue by Munnster83** [vbudilov/aws-cognito-ionic2#3]
Currently when registering as a user they are shown in the user pool, but in the federated identities they are showing as unauthenticated? 

If they are unauthenticated then I cant let them use the likes of DynamoDb or S3, is there something I am missing?

Does this relate to #2 ?

**Comment by vbudilov** [comment]
Per documentation: "Users can begin their life in an application as unauthenticated guests. Eventually they may decide to log in using one of the supported identity providers. Amazon Cognito will ensure that an old identity retains the same unique identifier as the new one, and the profile data will be merged automatically."

Basically, it's up to you to give unauth and auth users the access that you think they need. If you wanted to, your unauthenticated users would be able to access S3 and DDB, but I would strongly discourage that (especially for write access).
