### ISSUE TITLE
getCognitoIdentity returns null

### ISSUE THREAD

**Issue by vinodhum** [vbudilov/aws-cognito-ionic2#4]
Hi, 
when I try to get cognitoUtil.getCognitoIdentity() it returns null
any idea what am I doing wrong ?

**Comment by vbudilov** [comment]
Hi @vinodhum , 

Can you provide more info? Which changes have you done to the original code? 

Vladimir

**Comment by vbudilov** [comment]
@vinodhum , looks like you've double-posted this in the other repo: https://github.com/awslabs/aws-cognito-angular2-quickstart

I'm closing this one and will continue the conversation on the other thread. 

Thanks,
Vladimir
