### ISSUE TITLE
any examples on integrating dynamodb to this?

### ISSUE THREAD

**Issue by rohitkumarvinay** [vbudilov/aws-cognito-ionic2#5]
I am trying to build a CRUD application with this quickstart, any examples on how to store data from the mobile app to dynamodb.
Thank you

**Comment by vbudilov** [comment]
Hi @rohitkumarvinay , 

Here's almost the same code (without the ionic 2 part) that demonstrates the DynamoDB functionality: https://github.com/awslabs/aws-cognito-angular2-quickstart

Vladimir

**Comment by rohitkumarvinay** [comment]
I can add the ddb files to this, including createResource.sh?
