### ISSUE TITLE
[Documentation Error] 

### ISSUE THREAD

**Issue by icarosp** [vbudilov/aws-cognito-ionic2#8]
Hello! First of all, great work building this project! It is helping me a lot to understand the workflow between cognito <> ionic.

 I was reading the documentation and I found an error while trying to clone using the following command:

**git clone --depth 1 git@github.com:vbudilov/aws-cognito-ionic2.git**

I could fix it by replacing the url repository to **https://github.com/vbudilov/aws-cognito-ionic2.git**

So the command that worked for me was: 

**git clone --depth 1 https://github.com/vbudilov/aws-cognito-ionic2.git**

Should I submit a PR changing it?

Thanks!

**Comment by vbudilov** [comment]
Thanks. If you have your ssh keys setup the original line would work for you.
